Algoritmo "3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/09/2023
Var
// Seção de Declarações das variáveis 
     numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para numero de 1 ate 10 passo 1 faca
escreval(numero)
fimpara

Fimalgoritmo